version: "3.8"

services:
    nginx:
        build:
            context: './../'
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - '../app:/var/www/weather_forecast'
        depends_on:
            - php
            - db
        ports:
            - "8080:80"
        networks:
            - internal
    php:
        build:
            context: './../'
            dockerfile: docker/php/Dockerfile
        volumes:
            - '../app:/var/www/weather_forecast'
        networks:
            - internal
        depends_on:
            -   db
        environment:
            - XDEBUG_CONFIG
            - PHP_IDE_CONFIG
    db:
        image: postgres:${POSTGRES_VERSION}-alpine
        environment:
            POSTGRES_DB: "${POSTGRES_DB}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - '5432:5432'
        restart: always
        networks:
            - internal
    redis:
        image: redis:${REDIS_VERSION}
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data/redis
        networks:
            - internal

networks:
    internal:
        driver: bridge
volumes:
    db-data:
